/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Code.Main;
import audio.SoundJLayer;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.FloatControl;
import javax.sound.sampled.Mixer;
import javax.sound.sampled.Port;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import resources.LocalizationUtil;
import static resources.LocalizationUtil.localizedResourceBundle;

/**
 * This class is the screen of <code>Options</code>, this is where the
 * player sets his/hers settings
 *@author Ben Gilad and Asaf Yeshayahu
 *@version %I%
 *@see GUI.FormLobby has the options button
 *@see GUI.FormGame has the options button
 *@since 1.0
 */
public class FormOptions extends javax.swing.JFrame {

    /**
     * Play {@code ImageIcon}, used with the player controls
     * @see FormOptions#btnPlayActionPerformed(java.awt.event.ActionEvent)
     * @see audio.SoundJLayer
     */
    ImageIcon play;
    
    /**
     * Pause {@code ImageIcon}, used with the player controls
     * @see FormOptions#btnPlayActionPerformed(java.awt.event.ActionEvent)
     * @see audio.SoundJLayer
     */
    ImageIcon pause;
    
    /**
     * Creates a new form FormOptions
     */
    public FormOptions(){
        localizedResourceBundle = ResourceBundle.getBundle(
                "resources.Bundle", new Locale("en_US"));
        initComponents();
        setPlayerControls();
        updateCaptions();
        this.setVisible(true);
    }
    
    /**
     * Constructor for <b>FormOptions</b> form, creates the form 
     * @param parent The parent window (Previous window)
     */
    public FormOptions(JFrame parent){
        initComponents();
        setPlayerControls();
        updateCaptions();
        this.setVisible(true);
    }

    /**
     * This method changes the <i>localization</i> and updates the 
     * text to different <i>language</i>
     * @see resources.LocalizationUtil
     */
    public void updateCaptions(){
        LocalizationUtil.localizedResourceBundle = ResourceBundle.getBundle
        ("resources.Bundle");
        
        labVolume.setText(localizedResourceBundle.getString("FormOptions.labVolume"));
          labAbusiveLanguage.setText(localizedResourceBundle.getString("FormOptions.labAbusiveLanguage"));
                        this.setTitle(localizedResourceBundle.getString("FormOptions.title"));
                        
    }
        
    /**
     * Sets the player buttons, such as mute and play / pause button
     * @see audio.SoundJLayer The mp3 player
     * @see #btnPlay play / pause
     * @see SoundJLayer#setGain(float) set volume + mute
     */
    public void setPlayerControls(){
        
        // add icons for interchangeablity (play / pause)
        play = new ImageIcon("src\\GUI\\play.png");
        pause = new ImageIcon("src\\GUI\\pause.png");
        
        sliderVolume.setValue(SoundJLayer.volumeLevel);
        
        if(SoundJLayer.isPaused == false){
            btnPlay.setIcon(pause);
        }
        else{
             btnPlay.setIcon(play);
        }
        
        if(SoundJLayer.isMuted == true){
            musicCheck.setSelected(true);
        }
        else{
            musicCheck.setSelected(false);
        }
    }
    /**
     * Updates the the parent and this form with the locale change
     */
//    public void btnRadioUpdateLocale(){
//        String selectedLanguage = btnGrpLanguage.getSelection().getActionCommand();
//        localizedResourceBundle = ResourceBundle.getBundle(
//                "resources.Bundle", new Locale(selectedLanguage));
//        
//        this.setTitle(localizedResourceBundle.getString("FormLogin.title"));
//        labVolume.setText(localizedResourceBundle.getString(
//                "FormOptions.labVolume.text"));
//        labAbusiveLanguage.setText(localizedResourceBundle.getString(
//                "FormOptions.labAbusiveLanguage.text"));
//        labLanguage.setText(localizedResourceBundle.getString(
//                "FormOptions.labLanguage.text"));
//        radioEnglish.setText(localizedResourceBundle.getString(
//                "FormOptions.radioEnglish.text"));
//        radioHebrew.setText(localizedResourceBundle.getString(
//                "FormOptions.radioHebrew.text"));
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpLanguage = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        volumePanel = new javax.swing.JPanel();
        labVolume = new javax.swing.JLabel();
        musicCheck = new javax.swing.JCheckBox();
        lblMute = new javax.swing.JLabel();
        sliderVolume = new javax.swing.JSlider();
        abusiveLanguagePanel = new javax.swing.JPanel();
        chkboxAbusiveLanguage = new javax.swing.JCheckBox();
        labAbusiveLanguage = new javax.swing.JLabel();
        lblSettings = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Options");
        setBackground(new java.awt.Color(153, 255, 153));
        setLocationByPlatform(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        volumePanel.setBackground(new java.awt.Color(153, 255, 153));

        labVolume.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labVolume.setText("Volume");

        musicCheck.setBackground(new java.awt.Color(153, 255, 153));
        musicCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicCheckActionPerformed(evt);
            }
        });

        lblMute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/mute.png"))); // NOI18N
        lblMute.setPreferredSize(new java.awt.Dimension(128, 128));

        sliderVolume.setBackground(new java.awt.Color(153, 255, 153));
        sliderVolume.setToolTipText("");
        sliderVolume.setValue(100);
        sliderVolume.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderVolumeStateChanged(evt);
            }
        });

        javax.swing.GroupLayout volumePanelLayout = new javax.swing.GroupLayout(volumePanel);
        volumePanel.setLayout(volumePanelLayout);
        volumePanelLayout.setHorizontalGroup(
            volumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(volumePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labVolume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(sliderVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMute, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(musicCheck)
                .addContainerGap())
        );
        volumePanelLayout.setVerticalGroup(
            volumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labVolume, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, volumePanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(volumePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMute, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musicCheck))
                .addContainerGap())
        );

        abusiveLanguagePanel.setBackground(new java.awt.Color(153, 255, 153));

        chkboxAbusiveLanguage.setBackground(new java.awt.Color(153, 255, 153));
        chkboxAbusiveLanguage.setEnabled(false);
        chkboxAbusiveLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxAbusiveLanguageActionPerformed(evt);
            }
        });

        labAbusiveLanguage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labAbusiveLanguage.setText("Abusive Language Filter");
        labAbusiveLanguage.setEnabled(false);

        javax.swing.GroupLayout abusiveLanguagePanelLayout = new javax.swing.GroupLayout(abusiveLanguagePanel);
        abusiveLanguagePanel.setLayout(abusiveLanguagePanelLayout);
        abusiveLanguagePanelLayout.setHorizontalGroup(
            abusiveLanguagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abusiveLanguagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labAbusiveLanguage)
                .addGap(182, 182, 182)
                .addComponent(chkboxAbusiveLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        abusiveLanguagePanelLayout.setVerticalGroup(
            abusiveLanguagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abusiveLanguagePanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(abusiveLanguagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkboxAbusiveLanguage)
                    .addComponent(labAbusiveLanguage))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/settings.jpg"))); // NOI18N

        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblSettings)
                .addGap(0, 401, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPlay)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(abusiveLanguagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(volumePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 28, Short.MAX_VALUE)))
                    .addGap(29, 29, 29)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblSettings)
                .addGap(84, 84, 84)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 218, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(113, 113, 113)
                    .addComponent(volumePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(abusiveLanguagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(97, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkboxAbusiveLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxAbusiveLanguageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkboxAbusiveLanguageActionPerformed
    
    /**
     * <i>Action</i> when clicked <b>button</b> mutes / un-mutes the game
     * @param evt the event itself
     */
    private void musicCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicCheckActionPerformed
        // mute or unmute the sound
        if(musicCheck.isSelected()){
            SoundJLayer.isMuted = true;
            SoundJLayer.setGain(0);
        }
        else{
            SoundJLayer.isMuted = false;
            SoundJLayer.volumeLevel = sliderVolume.getValue();
            SoundJLayer.setGain(sliderVolume.getValue() / 100f);
        }
    }//GEN-LAST:event_musicCheckActionPerformed

    /**
     * <i>Action</i> when slider is moved, handles volume gain
     * @see audio.SoundJLayer#setGain(float) set volume function
     * @param evt the event itself
     */
    private void sliderVolumeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderVolumeStateChanged
        //change volume according to slider
        SoundJLayer.volumeLevel = sliderVolume.getValue();
        
        if(SoundJLayer.isMuted == false){
            SoundJLayer.setGain(sliderVolume.getValue() / 100f);
        }
    }//GEN-LAST:event_sliderVolumeStateChanged

     /**
     * <i>Action</i> when clicked <b>button</b> play / pauses music
     * @param evt the event itself
     */
    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        
        /* play / pause music */
        
        // Player is working
        if(SoundJLayer.isPaused == false){

            //set icons
            btnPlay.setIcon(play);

            //inform the player to pause
            Main.player.pause();
        }

        // Player isn't working
        else{

            //set icons
            btnPlay.setIcon(pause);

            //inform thread to resume
             Main.player.play();
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    /**
     * Default main form method (SWING DEFAULT)
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abusiveLanguagePanel;
    private javax.swing.ButtonGroup btnGrpLanguage;
    private javax.swing.JButton btnPlay;
    private javax.swing.JCheckBox chkboxAbusiveLanguage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labAbusiveLanguage;
    private javax.swing.JLabel labVolume;
    private javax.swing.JLabel lblMute;
    private javax.swing.JLabel lblSettings;
    private javax.swing.JCheckBox musicCheck;
    private javax.swing.JSlider sliderVolume;
    private javax.swing.JPanel volumePanel;
    // End of variables declaration//GEN-END:variables
}
